from __future__ import annotations


def render_dashboard() -> str:
    return r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>EdgeChainDB Cluster Monitor · Network Operations</title>
<style>
:root{--bg:#06101c;--panel:#0d1b2b;--panel2:#12243a;--panel3:#182d47;--text:#edf5ff;--muted:#8fa4bd;--line:#263e5b;--ok:#36d98b;--bad:#ff6f7d;--warn:#ffd166;--accent:#68a9ff;--cyan:#58d6e8;--shadow:0 18px 50px rgba(0,0,0,.28)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 20% -10%,#153b61 0,transparent 32%),linear-gradient(145deg,#06101c,#091828 55%,#06101c);color:var(--text);font:14px/1.45 Inter,Segoe UI,system-ui,sans-serif;min-height:100vh}
header{padding:22px 28px;border-bottom:1px solid var(--line);background:rgba(6,16,28,.86);position:sticky;top:0;z-index:10;backdrop-filter:blur(14px);display:flex;justify-content:space-between;gap:20px;align-items:center}h1{font-size:24px;margin:0 0 3px}.subtitle{color:var(--muted)}.header-state{display:flex;gap:10px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.dot{width:9px;height:9px;border-radius:50%;display:inline-block;background:var(--warn);box-shadow:0 0 13px currentColor}.dot.ok{background:var(--ok)}.dot.bad{background:var(--bad)}
main{max-width:1680px;margin:auto;padding:22px}.toolbar,.metrics{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}button,a.button,select,input{border:1px solid var(--line);background:var(--panel2);color:var(--text);padding:9px 12px;border-radius:9px;text-decoration:none;font-weight:650}button{cursor:pointer}button:hover,a.button:hover{border-color:var(--accent);transform:translateY(-1px)}button.danger{border-color:#783741;background:#391c28}button.warn{border-color:#736132;background:#342d19}button:disabled{opacity:.45;cursor:not-allowed;transform:none}.card{background:linear-gradient(145deg,rgba(18,36,58,.96),rgba(11,27,44,.96));border:1px solid var(--line);border-radius:15px;padding:16px;box-shadow:var(--shadow)}.metric{min-width:150px;flex:1}.metric strong{display:block;font-size:26px;letter-spacing:-.03em}.metric span{color:var(--muted);font-size:12px}.metric small{display:block;color:var(--muted);margin-top:3px}.ok-text{color:var(--ok)}.bad-text{color:var(--bad)}.warn-text{color:var(--warn)}
.layout{display:grid;grid-template-columns:1.15fr .85fr;gap:16px;margin-bottom:16px}.wide{grid-column:1/-1}.section-title{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px}.section-title h2{margin:0;font-size:17px}.section-title small{color:var(--muted)}
.network-map{display:grid;grid-template-columns:minmax(180px,.8fr) 38px minmax(260px,1.2fr) 38px minmax(180px,.8fr);align-items:center;gap:8px}.network-node{background:var(--panel3);border:1px solid var(--line);border-radius:12px;padding:15px;text-align:center;min-height:110px;display:flex;flex-direction:column;justify-content:center}.network-node strong{font-size:17px}.arrow{font-size:27px;text-align:center;color:var(--cyan)}.network-details{margin-top:12px;display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.mini{background:rgba(6,16,28,.42);border:1px solid var(--line);border-radius:10px;padding:10px}.mini span{color:var(--muted);display:block;font-size:11px}.mini b{font-size:13px;word-break:break-all}
.services{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:9px}.service{background:rgba(6,16,28,.42);border:1px solid var(--line);border-radius:11px;padding:12px}.service h3{margin:0 0 8px;display:flex;justify-content:space-between}.kv{display:grid;grid-template-columns:1fr 1fr;gap:5px 10px;color:var(--muted);font-size:12px}.kv b{color:var(--text);font-weight:650;overflow:hidden;text-overflow:ellipsis}.badge{font-size:10px;border-radius:20px;padding:3px 8px;background:#263d5d;text-transform:uppercase;letter-spacing:.04em}.badge.running,.badge.live,.badge.healthy,.badge.completed{color:var(--ok)}.badge.exited,.badge.dead,.badge.failed,.badge.unhealthy,.badge.stale,.badge.never{color:var(--bad)}.badge.paused,.badge.delayed,.badge.restarting,.badge.running_benchmark,.badge.restarting_gateway{color:var(--warn)}
.devices{display:grid;grid-template-columns:repeat(auto-fill,minmax(285px,1fr));gap:10px}.device{background:linear-gradient(145deg,var(--panel2),#102035);border:1px solid var(--line);border-radius:13px;padding:13px;position:relative;overflow:hidden}.device:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--muted)}.device.live:before{background:var(--ok)}.device.delayed:before{background:var(--warn)}.device.stale:before,.device.never:before{background:var(--bad)}.device h3{margin:0 0 9px;display:flex;justify-content:space-between;gap:8px}.device-values{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:10px 0}.value{background:rgba(6,16,28,.5);border:1px solid #223b58;border-radius:9px;padding:8px;text-align:center}.value b{display:block;font-size:15px}.value span{font-size:9px;color:var(--muted);text-transform:uppercase}.actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px}.actions button{font-size:10px;padding:5px 7px}
.table-wrap{overflow:auto;max-height:480px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line);font-size:11px;white-space:nowrap}th{color:var(--muted);position:sticky;top:0;background:var(--panel2);z-index:2}td.payload{white-space:normal;min-width:240px;color:#bcd2ea}code{color:#b9d8ff}.error{color:var(--bad);white-space:pre-wrap}.muted{color:var(--muted)}
.log-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:10px}.logs{height:420px;overflow:auto;background:#030a12;border:1px solid #1d334c;border-radius:10px;padding:12px;font:11px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word;color:#c7d7e8}.log-line{display:block;border-bottom:1px solid rgba(70,100,130,.12);padding:2px 0}.log-line.error,.log-line.ERROR{color:#ff9aa4}.log-line.warning,.log-line.WARNING{color:#ffe08a}.log-line.info,.log-line.INFO{color:#c9e1fa}.log-line.debug,.log-line.DEBUG{color:#788da4}.log-count{color:var(--muted)}
.progress{height:8px;border-radius:10px;background:#07121f;overflow:hidden;border:1px solid var(--line)}.progress i{height:100%;display:block;background:linear-gradient(90deg,var(--accent),var(--cyan));width:0}.benchmark-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.chart{height:80px;width:100%;margin-top:8px}.chart polyline{fill:none;stroke:var(--cyan);stroke-width:2}.chart .gridline{stroke:#263e5b;stroke-width:1}
.toast{position:fixed;right:20px;bottom:20px;background:#152a43;border:1px solid var(--line);border-radius:10px;padding:12px 15px;box-shadow:var(--shadow);display:none;max-width:430px;z-index:30}.toast.bad{border-color:#7b3540;color:#ffc2c7}.toast.ok{border-color:#2b7456;color:#bdf5d6}
@media(max-width:1050px){.layout{grid-template-columns:1fr}.network-map{grid-template-columns:1fr}.arrow{transform:rotate(90deg)}header{position:static;align-items:flex-start;flex-direction:column}.header-state{justify-content:flex-start}.benchmark-grid{grid-template-columns:1fr}}@media(max-width:600px){main{padding:12px}header{padding:16px}.device-values{grid-template-columns:1fr 1fr}.metric{min-width:125px}.logs{height:330px}}
</style>
</head>
<body>
<header>
 <div><h1>EdgeChainDB Cluster Monitor</h1><div class="subtitle">Live gateway, 20-device telemetry, Docker network, benchmark, and logs · monitor port 3030</div></div>
 <div class="header-state"><span><i id="connectionDot" class="dot"></i> <b id="connectionText">Connecting</b></span><span class="muted" id="lastUpdate">—</span></div>
</header>
<main>
<div class="toolbar">
 <button onclick="allAction('start')">Start all devices</button><button onclick="allAction('stop')" class="danger">Stop all</button><button onclick="allAction('restart')">Restart all</button><button onclick="allAction('pause')" class="warn">Pause all</button><button onclick="allAction('unpause')">Resume all</button>
 <a class="button" href="/benchmark/report" target="_blank">Latest benchmark report</a><a class="button" href="/docs" target="_blank">API documentation</a>
</div>
<div class="metrics" id="metrics"></div>

<div class="layout">
 <section class="card">
  <div class="section-title"><h2>Private network topology</h2><small id="networkChecked">Waiting for Docker</small></div>
  <div id="networkMap" class="network-map"></div><div id="networkDetails" class="network-details"></div>
 </section>
 <section class="card">
  <div class="section-title"><h2>Gateway and orchestration</h2><small id="controller"></small></div>
  <div id="services" class="services"></div>
  <svg id="rateChart" class="chart" viewBox="0 0 500 80" preserveAspectRatio="none"><line class="gridline" x1="0" y1="70" x2="500" y2="70"></line><polyline points=""></polyline></svg>
  <small class="muted">Recent cluster event-rate history</small>
 </section>
</div>

<section class="card wide" style="margin-bottom:16px">
 <div class="section-title"><h2>Device fleet and current sensor values</h2><small id="deviceSummary">—</small></div>
 <div class="devices" id="devices"></div>
</section>

<div class="layout">
 <section class="card">
  <div class="section-title"><h2>Recent signed telemetry</h2><small>Newest first</small></div>
  <div class="table-wrap" id="events"></div>
 </section>
 <section class="card">
  <div class="section-title"><h2>Benchmark state</h2><small id="benchmarkUpdated">—</small></div>
  <div id="benchmark"></div>
 </section>
</div>

<section class="card wide">
 <div class="section-title"><h2>Container logs</h2><span class="log-count" id="logCount">—</span></div>
 <div class="log-toolbar">
  <select id="logService" onchange="loadLogs(true)"></select>
  <select id="logTail" onchange="loadLogs(true)"><option value="100">100 lines</option><option value="250" selected>250 lines</option><option value="500">500 lines</option><option value="1000">1000 lines</option></select>
  <select id="logLevel"><option value="ALL">All levels</option><option value="ERROR">Errors</option><option value="WARNING">Warnings</option><option value="INFO">Info</option><option value="DEBUG">Debug</option></select>
  <button onclick="loadLogs(true)">Refresh logs</button><button id="logPause" onclick="toggleLogs()">Pause auto-refresh</button>
 </div>
 <div id="logs" class="logs">Waiting for container logs…</div>
</section>
</main>
<div id="toast" class="toast"></div>
<script>
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={rateHistory:[],logPaused:false,services:[],loadingLogs:false,loadingAll:false};
async function api(url,options){const r=await fetch(url,options);const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(typeof data==='string'?data:JSON.stringify(data));return data}
function toast(message,kind='ok'){const e=$('toast');e.textContent=message;e.className='toast '+kind;e.style.display='block';clearTimeout(e.timer);e.timer=setTimeout(()=>e.style.display='none',4200)}
function fmtBytes(n){n=Number(n||0);const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function fmtAge(ms){if(ms===null||ms===undefined)return 'never';if(ms<1000)return `${ms} ms`;if(ms<60000)return `${(ms/1000).toFixed(1)} s`;if(ms<3600000)return `${(ms/60000).toFixed(1)} min`;return `${(ms/3600000).toFixed(1)} h`}
function fmtNum(v,d=1){return Number(v||0).toFixed(d)}
function metric(label,value,detail='',klass=''){return `<div class="card metric ${klass}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></div>`}
function badge(value){return `<span class="badge ${esc(value)}">${esc(value||'unknown')}</span>`}
function sensor(payload,key,scale=1,suffix=''){const v=payload?.[key];return v===undefined||v===null?'—':`${(Number(v)/scale).toFixed(scale===1?0:2)}${suffix}`}
function setConnection(ok,error=''){const dot=$('connectionDot');dot.className='dot '+(ok?'ok':'bad');$('connectionText').textContent=ok?'Live':'Disconnected';if(error)$('lastUpdate').textContent=error}
function chart(rate){state.rateHistory.push(Number(rate||0));if(state.rateHistory.length>60)state.rateHistory.shift();const max=Math.max(...state.rateHistory,1);const points=state.rateHistory.map((v,i)=>`${state.rateHistory.length===1?0:i/(state.rateHistory.length-1)*500},${70-v/max*62}`).join(' ');$('rateChart').querySelector('polyline').setAttribute('points',points)}
function renderNetwork(network,cluster){const n=network.networks?.[0];const summary=cluster.summary;const gateway=cluster.services.find(s=>s.service==='gateway');$('networkMap').innerHTML=`<div class="network-node"><span class="muted">Browser control plane</span><strong>localhost:3030</strong><small>Dashboard and observability API</small></div><div class="arrow">⇄</div><div class="network-node"><span class="muted">${esc(n?.driver||'Docker bridge')}</span><strong>${esc(n?.name||'edgechain-iot-net')}</strong><small>${n?.internal?'Internal / isolated':'External access enabled'} · ${esc(n?.subnets?.[0]?.subnet||'subnet unavailable')}</small></div><div class="arrow">⇄</div><div class="network-node"><span class="muted">Connected workloads</span><strong>${esc(n?.connected_containers??cluster.summary.total_devices+1)} containers</strong><small>${summary.running_devices} devices running · gateway ${esc(gateway?.state||'unknown')}</small></div>`;
 $('networkDetails').innerHTML=[['Network RX',fmtBytes(summary.network_rx_bytes)],['Network TX',fmtBytes(summary.network_tx_bytes)],['Recent traffic',`${summary.events_last_minute} events/min`],['Gateway IP',gateway?.networks?.[0]?.ip_address||'—'],['Gateway uptime',`${fmtNum(cluster.gateway_uptime_seconds||0,1)} s`],['Network checked',network.checked_at||'—']].map(([a,b])=>`<div class="mini"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('');$('networkChecked').textContent=network.available?(network.checked_at||'connected'):(network.error||'network unavailable')}
function renderServices(cluster){const values=cluster.services||[];$('services').innerHTML=values.map(s=>{const m=s.metrics||{};return `<article class="service"><h3>${esc(s.service)} ${badge(s.health||s.state)}</h3><div class="kv"><span>State</span><b>${esc(s.state)}</b><span>CPU</span><b>${fmtNum(m.cpu_percent,2)}%</b><span>Memory</span><b>${fmtBytes(m.memory_bytes)} / ${fmtBytes(m.memory_limit_bytes)}</b><span>Network</span><b>↓${fmtBytes(m.network_rx_bytes)} ↑${fmtBytes(m.network_tx_bytes)}</b><span>Restarts</span><b>${esc(s.restart_count||0)}</b><span>Container</span><b>${esc(s.container_id||'—')}</b></div></article>`}).join('')||'<p class="muted">Service runtime information is unavailable.</p>'}
function renderDevices(cluster){$('deviceSummary').textContent=`${cluster.summary.live_devices} live · ${cluster.summary.delayed_devices} delayed · ${cluster.summary.stale_devices} stale`;$('devices').innerHTML=cluster.devices.map(d=>{const p=d.last_payload||{},m=d.metrics||{},net=d.networks?.[0]||{};return `<article class="device ${esc(d.telemetry_status)}"><h3><span>${esc(d.service)}</span>${badge(d.telemetry_status)}</h3><div class="device-values"><div class="value"><b>${sensor(p,'temperature_milli_celsius',1000,'°C')}</b><span>Temperature</span></div><div class="value"><b>${sensor(p,'humidity_basis_points',100,'%')}</b><span>Humidity</span></div><div class="value"><b>${sensor(p,'battery_millivolts',1000,'V')}</b><span>Battery</span></div><div class="value"><b>${sensor(p,'quality',1,'')}</b><span>Quality</span></div></div><div class="kv"><span>Runtime</span><b>${esc(d.state)} / ${esc(d.health||'no health')}</b><span>Sequence</span><b>${esc(d.last_sequence)}</b><span>Last telemetry</span><b>${fmtAge(d.last_event_age_ms)} ago</b><span>Rate</span><b>${fmtNum(d.events_per_second,2)} evt/s</b><span>Finality</span><b>${d.finalized===null?'—':d.finalized?`block ${esc(d.block_height)}`:'pending'}</b><span>Clock lag</span><b>${d.clock_lag_ms===null?'—':`${esc(d.clock_lag_ms)} ms`}</b><span>CPU / memory</span><b>${fmtNum(m.cpu_percent,2)}% / ${fmtBytes(m.memory_bytes)}</b><span>RX / TX</span><b>${fmtBytes(m.network_rx_bytes)} / ${fmtBytes(m.network_tx_bytes)}</b><span>IP</span><b>${esc(net.ip_address||'—')}</b><span>Restarts</span><b>${esc(d.restart_count||0)}</b></div><div class="actions"><button onclick="oneAction('${esc(d.service)}','start')">Start</button><button onclick="oneAction('${esc(d.service)}','stop')" class="danger">Stop</button><button onclick="oneAction('${esc(d.service)}','restart')">Restart</button><button onclick="oneAction('${esc(d.service)}','pause')" class="warn">Pause</button><button onclick="oneAction('${esc(d.service)}','unpause')">Resume</button><button onclick="selectLog('${esc(d.service)}')">Logs</button></div></article>`}).join('')}
function renderEvents(events){$('events').innerHTML=`<table><thead><tr><th>Received</th><th>Device</th><th>Seq</th><th>Type</th><th>Values</th><th>Block</th></tr></thead><tbody>${events.map(e=>`<tr><td>${esc(e.received_at||'—')}</td><td>${esc(e.device_id)}</td><td>${esc(e.sequence)}</td><td>${esc(e.event_type)}</td><td class="payload">${esc(JSON.stringify(e.payload))}</td><td>${e.finalized?`#${esc(e.block_height)} ✓`:'pending'}</td></tr>`).join('')}</tbody></table>`}
function renderBenchmark(b){const status=b.status||'not_started';const phases=['waiting_for_cluster','quiescing_devices','running_benchmark','restarting_gateway','completed'];let index=phases.indexOf(status);if(status==='failed')index=phases.length;const pct=status==='not_started'?0:Math.min(100,Math.max(8,(index+1)/phases.length*100));$('benchmarkUpdated').textContent=b.updated_at||'—';$('benchmark').innerHTML=`<div class="benchmark-grid"><div class="mini"><span>Status</span><b>${badge(status)}</b></div><div class="mini"><span>Suite exit code</span><b>${esc(b.suite_exit_code??'—')}</b></div><div class="mini"><span>Recovery</span><b>${b.recovery_ok===undefined?'—':b.recovery_ok?'PASS':'FAIL'}</b></div><div class="mini"><span>Stopped devices</span><b>${esc(b.stopped_devices??'—')}</b></div></div><div style="margin-top:12px" class="progress"><i style="width:${pct}%"></i></div>${b.error?`<p class="error">${esc(b.error)}</p>`:''}<p><a class="button" href="/benchmark/report" target="_blank">Open report</a> <button onclick="selectLog('test')">Show test logs</button></p>`}
function updateLogServices(cluster){const values=['gateway','run','test',...cluster.devices.map(d=>d.service)];if(JSON.stringify(values)===JSON.stringify(state.services))return;state.services=values;const current=$('logService').value||'gateway';$('logService').innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');$('logService').value=values.includes(current)?current:'gateway'}
async function loadAll(){if(state.loadingAll)return;state.loadingAll=true;try{const [cluster,network,events,benchmark]=await Promise.all([api('/cluster/state?include_metrics=true'),api('/cluster/network'),api('/cluster/events?limit=80'),api('/benchmark/status')]);const stats=cluster.ledger,sm=cluster.summary;$('metrics').innerHTML=metric('Live devices',`${sm.live_devices}/${sm.total_devices}`,`${sm.running_devices} containers running`,sm.live_devices===sm.total_devices?'ok-text':'warn-text')+metric('Event rate',`${fmtNum(sm.events_per_second,2)} /s`,`${sm.events_last_minute} in last minute`)+metric('Ledger events',stats.events,`${stats.finalized_events} finalized`)+metric('Blocks',stats.blocks,`${stats.finalized_blocks} finalized`)+metric('Pending',stats.pending_events,stats.pending_events?'awaiting next block':'ledger caught up',stats.pending_events?'warn-text':'ok-text')+metric('Network RX',fmtBytes(sm.network_rx_bytes),'all project containers')+metric('Network TX',fmtBytes(sm.network_tx_bytes),'all project containers')+metric('Monitor','Port 3030','refresh every 2 seconds');$('controller').innerHTML=cluster.controller.available?`<span class="ok-text">Docker connected · ${esc(cluster.controller.project)}</span>`:`<span class="bad-text">${esc(cluster.controller.error||'Docker unavailable')}</span>`;renderNetwork(network,cluster);renderServices(cluster);renderDevices(cluster);renderEvents(events);renderBenchmark(benchmark);updateLogServices(cluster);chart(sm.events_per_second);setConnection(true);$('lastUpdate').textContent=`Updated ${new Date().toLocaleTimeString()}`;if(!state.logPaused)loadLogs(false)}catch(e){setConnection(false,String(e));toast(String(e),'bad')}finally{state.loadingAll=false}}
async function oneAction(service,action){try{const r=await api(`/cluster/devices/${service}/${action}`,{method:'POST'});toast(`${service}: ${action} → ${r.state}`);setTimeout(loadAll,500)}catch(e){toast(String(e),'bad')}}
async function allAction(action){try{const r=await api(`/cluster/devices/${action}`,{method:'POST'});toast(`${action}: ${r.results.length} devices, success=${r.ok}`);setTimeout(loadAll,700)}catch(e){toast(String(e),'bad')}}
function selectLog(service){$('logService').value=service;loadLogs(true);document.querySelector('.logs').scrollIntoView({behavior:'smooth',block:'center'})}
function toggleLogs(){state.logPaused=!state.logPaused;$('logPause').textContent=state.logPaused?'Resume auto-refresh':'Pause auto-refresh';toast(state.logPaused?'Log auto-refresh paused':'Log auto-refresh resumed')}
function parseLevel(line){try{const idx=line.indexOf('{');if(idx>=0){const obj=JSON.parse(line.slice(idx));return obj.level||'INFO'}}catch{}if(/ERROR|Traceback|Exception|failed/i.test(line))return 'ERROR';if(/WARN|retry|degraded/i.test(line))return 'WARNING';if(/DEBUG/i.test(line))return 'DEBUG';return 'INFO'}
async function loadLogs(force){if(state.loadingLogs||(!force&&state.logPaused))return;const service=$('logService').value;if(!service)return;state.loadingLogs=true;try{const value=await api(`/cluster/logs/${encodeURIComponent(service)}?tail=${$('logTail').value}`);const level=$('logLevel').value;const lines=value.lines.filter(line=>level==='ALL'||parseLevel(line)===level);const box=$('logs'),nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.innerHTML=lines.map(line=>`<span class="log-line ${parseLevel(line)}">${esc(line)}</span>`).join('')||'<span class="muted">No matching log lines.</span>';$('logCount').textContent=`${value.line_count} collected · ${lines.length} shown · ${value.service}`;if(force||nearBottom)box.scrollTop=box.scrollHeight}catch(e){$('logs').innerHTML=`<span class="error">${esc(e)}</span>`;$('logCount').textContent='log unavailable'}finally{state.loadingLogs=false}}
$('logLevel').addEventListener('change',()=>loadLogs(true));loadAll();setInterval(loadAll,2000);
</script>
</body></html>'''
